name: Deploy to Server whenever push on master

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH and authenticate with your server
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.93.216.55 >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: SSH into the server and deploy the code
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no root@34.93.216.55 << 'EOF'
            cd /var/www/html
            git pull origin master  # Pull the latest changes from the master branch
            # Any additional commands you need for deployment (e.g., restarting services, installing dependencies)
          EOF
