name: Deploy on push to master

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up SSH
        uses: webfactory/ssh-agent@v0.5.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SERVER_USER}}
          PORT: 80
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          scripts: 'cd /var/www/html/ && git pull'

    #  - name: Deploy Code
      #  run: |
       #   ssh -o StrictHostKeyChecking=no maruthiwork0009@34.93.216.55 'cd /path/to/your/project && git pull'
